### ISSUE TITLE
管理者権限の追加

### ISSUE THREAD

**Issue by musashi-634** [musashi-634/taskwith#78]
## 概要
管理者権限を追加する。

## 目的
管理者のみ、組織の管理を行えるようにするため。

## タスク
- [x] 管理者権限を表す`is_admin`カラムを追加する。
- [x] 組織作成時に、作成者が組織の管理者となるようにする。
- [x] 管理者のみ、以下のことができるようにする。
   - [x] 組織関連
      - [ ] 組織の更新 <- issue #76 にて実装予定
      - [ ] 組織の削除 <- issue #77 にて実装予定
   - [x] 組織メンバー関連
      - [x] 組織メンバーの招待
      - [ ] 自分以外の組織メンバーの脱退（自分を脱退させることは不可とする） <- issue #70 にて実装予定
   - [x] 管理者関連
      - [x] 管理者権限の表示
      - [x] 自分以外の組織メンバーの管理者権限の変更（自分の管理者権限の変更は不可とする）
- [x] 管理者ユーザー削除時に、以下のように振る舞うよう設定する。
   - [x] 管理者が自分だけの場合、組織を削除する。
   - [x] 他にも管理者がいる場合、組織を削除しない。
- [x] seedにて管理者を設定する。
- [x] テーブルおよびER図
   - [x] 組織削除時にユーザーとの参照整合性が崩れないよう、usersテーブルに外部キー制約を追加する。
   - [x] usersテーブルに合わせ、他のテーブルにも外部キー制約を追加する。
   - [x] tasksテーブルの現状に合わせ、ER図から不要な属性およびリレーションを削除する。
